# live_config_reload = true

[font]
size = 18

  [font.offset]
  y = 16

  [font.glyph_offset]
  y = 9

  [font.normal]
  family = "Hack NF"

[window]
opacity = 0.9
decorations = "none"
dynamic_title = true
  [window.padding]
  x = 5
  y = 5

  [window.dimensions]
  columns = 120
  lines = 40

[cursor]
unfocused_hollow = true

  [cursor.style]
  blinking = "Never"

[env]
TERM = "xterm-256color"

[scrolling]
history = 10_000

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
        { action = "Copy", key = "C", mods = "Control|Shift" },
        { action = "Paste", key = "V", mods = "Control|Shift" }
]

[colors.primary]
background = "#1b1b1b"
foreground = "#ebdbb2"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"
